ami:
  servers:
    - host: asterisk1
    # - host: 172.18.0.2
      username: admin
      secret: P@$$w0rD!
    - host: asterisk2
    # - host: 172.18.0.3
      username: admin
      secret: P@$$w0rD!
voip_adapter:
  dial_template: PJSIP/kamailio/sip:%s@office.voip
  dial_context: queue-test
  dial_exten: s-CONNECT
operator_repo:
  operators:
    - 2003
    - 2004
    - 2005
