version: '3'
services:
  asterisk1:
    build: integration/1/asterisk
    container_name: asterisk1

  asterisk2:
    build: integration/1/asterisk
    container_name: asterisk2

  kamailio:
    build: integration/1/kamailio
    container_name: kamailio
    volumes:
      - "./integration/1/kamailio/etc:/etc/kamailio"
    healthcheck:
      test: ["CMD-SHELL", "test $(kamcmd dispatcher.list | grep 'FLAGS: AX' | wc -l) -eq 2"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      default:
        aliases:
          - office.voip
    
  sipp_op1:
    build: integration/1/sipp_op
    container_name: sipp_op1
    command: kamailio 2003 15000
    healthcheck:
      test: ["CMD-SHELL", "test -n \"$(ps | grep uas.xml | grep -v grep)\" && netstat -an | grep 5060"]
      interval: 10s
      timeout: 2s
      retries: 10
    depends_on:
      kamailio:
        condition: service_healthy

  sipp_op2:
    build: integration/1/sipp_op
    container_name: sipp_op2
    command: kamailio 2004 5000
    healthcheck:
      test: ["CMD-SHELL", "test -n \"$(ps | grep uas.xml | grep -v grep)\" && netstat -an | grep 5060"]
      interval: 10s
      timeout: 2s
      retries: 10
    depends_on:
      kamailio:
        condition: service_healthy

  sipp_op3:
    build: integration/1/sipp_op
    container_name: sipp_op3
    command: kamailio 2005 10000
    healthcheck:
      test: ["CMD-SHELL", "test -n \"$(ps | grep uas.xml | grep -v grep)\" && netstat -an | grep 5060"]
      interval: 10s
      timeout: 2s
      retries: 10
    depends_on:
      kamailio:
        condition: service_healthy

  # app:
  #   build:
  #     context: .
  #     dockerfile: integration/1/app/Dockerfile
  #   container_name: app
  #   healthcheck:
  #     test: ["CMD-SHELL", "test $(netstat -an | grep 5038 | wc -l) -eq 2"]
  #     interval: 10s
  #     timeout: 2s
  #     retries: 10
  #   depends_on:
  #     sipp_op1:
  #       condition: service_healthy
  #     sipp_op2:
  #       condition: service_healthy
  #     sipp_op3:
  #       condition: service_healthy

  # sipp_cl:
  #   build: integration/1/sipp_cl
  #   container_name: sipp_cl
  #   # command: kamailio -sf uac.xml -s 2003 -inf client_accounts.csv -infindex client_accounts.csv 0 -key line 4 -m 10
  #   command: kamailio -sf uac.xml -s 3000 -inf client_accounts.csv -infindex client_accounts.csv 0 -key line 4 -m 100
  #   depends_on:
  #     app:
  #       condition: service_healthy
      
