package ami

const (
	keyResponse    = "Response"
	keyAction      = "Action"
	keyActionID    = "ActionID"
	keyUsername    = "Username"
	keySecret      = "Secret"
	keyEvent       = "Event"
	keyChannel     = "Channel"
	keyChannel1    = "Channel1"
	keyChannel2    = "Channel2"
	keyCause       = "Cause"
	keyCallerIDNum = "CallerIDNum"
	keyCommand     = "Command"
	keyCommandID   = "CommandId"
	keyResult      = "Result"
	keyTone        = "Tone"

	fieldUsername       = "Username"
	fieldSecret         = "Secret"
	fieldChannel        = "Channel"
	fieldCause          = "Cause"
	fieldExten          = "Exten"
	fieldContext        = "Context"
	fieldPriority       = "Priority"
	fieldApplication    = "Application"
	fieldData           = "Data"
	fieldTimeout        = "Timeout"
	fieldCallerID       = "CallerID"
	fieldVariable       = "Variable"
	fieldValue          = "Value"
	fieldAccount        = "Account"
	fieldEarlyMedia     = "EarlyMedia"
	fieldAsync          = "Async"
	fieldCodecs         = "Codecs"
	fieldChannelID      = "ChannelId"
	fieldOtherChannelID = "OtherChannelId"
	fieldChannel1       = "Channel1"
	fieldChannel2       = "Channel2"
	fieldTone           = "Tone"
	fieldListItems      = "ListItems"

	agiCmdAnswer   = "ANSWER"
	agiCmdPlayback = "EXEC Playback"
	agiCmdSetMusic = "SET MUSIC"

	agiOn  = "on"
	agiOff = "off"

	actionAGI          = "AGI"
	actionHangup       = "Hangup"
	actionAsyncAGIExec = "AsyncAGIExec"
	actionOriginate    = "Originate"
	actionBridge       = "Bridge"
	actionSetvar       = "Setvar"

	success = "Success"
	goodbye = "Goodbye"
)
