ami:
  servers:
    - host: asterisk1
      username: admin
      secret: P@$$w0rD!
    - host: asterisk2
      username: admin
      secret: P@$$w0rD!
voip_adapter:
  tech_data: PJSIP/kamailio/sip:%s@office.voip
  context: queue-test
  exten: s-OPERATOR
operator_repo:
  operators:
    - 2003
    - 2004
    - 2005
