context: dqueue
ami:
  servers:
    - host: asterisk1
      username: admin
      secret: P@$$w0rD!
    - host: asterisk2
      username: admin
      secret: P@$$w0rD!
voip:
  tech_data: PJSIP/kamailio/sip:%s@office.voip
  context: dqueue
  exten: s-OPERATOR
operator:
  operators:
    - 2003
    - 2004
    - 2005
